export const ADD_TO_CART = "addToCart"
export const REMOVE_FROM_CART = "removeFromCart"
export const CART_RESET = "cartReset"
export const UPDATE_QUANTITY = "updateQuantity"
export const SET_CART = "setCart"
export const EMPTY_CART = "emptyCart"